name: HintsofVince
favicon: null
layout_spectrum: 0.5186049442272633
typography_spectrum: 0.37601370830088854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.550323887495324
  lightness: 0.4359007733874023
  saturation: 0.3892236896790564
  rhythmicContrast: 0.7780139958485961
purpose: []
